language: php
php:
  - nightly
  

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  
deploy:
 provider: heroku
 app:
  master: eventlab-project
  dev: eventlab-dev
 api_key:
  secure: bRsKy4l3MUrAHQL2QvzznIt4I6UVzXLZQRcbVuNKT/hNYNa+W+Z2l9FsAEdsdO/iu9EsYL0huD76LfYoun6F8N9ca04h16UcZHmC8gZPwbMRSRONUdYx0GtTyqFO877QoOAslHGe/dXV3N3CFA2Ndpnuh3lnYAV+IOr3ok4kMmY0KrvQMH10Gl7/+UcWH70KE5AYaWHg7wusWPHFJgVRTF/SOXEZu9XcYIHA0PRd2ijl5jJSbczifiiYBNHIE6xfpagkXaruIozqaiU6INrubu/MqkujzdC48854ktQ2zh7SI8g935HSGbpKeDRR10GuCyiSYmxYA7lO7asj4L2/tYA0IgJlmhgzSvBWLgtCj5e91ZPIoSc2jrchKByOkxuS7ws3dGmpWVZStGvTqWwEeiJCeqrWfjRiOxqbxCdrnBbtseWrzGtG0788FmBgKuAolXU8PKYyUPF3iKCyeQMv0qtdWOR26NCOA12HAyZndb+IGECfZ5YVaJqkd9qgCa/yoLCAANnYXMMvQC8e5ZCWIz2xg/kcBXhUl8w8kCqwn51LSpoPuupszYIPhR9SRmsytXBzLUmLcNj4+CPqVkyPzeEIOlyBv4OTwRv56J0qhrVCWZKMNVqsH/Z9+ilCGuDOi4Ns4lcdNf9QLbH+TNSK7KVXrb71/JzcLxK9num0MhY=
