coverage:
  precision: 2
  round: nearest
  range: "0...100"
  status:
    project:
      default:
        threshold: 50
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
  ignore:
    - "/app/Exceptions"
    - "/app/Providers/BroadcastServiceProvider.php"
    - "/app/Http/Middleware"
    - "/app/Http/Controllers/Auth"
    - "/app/Http/Controllers/EditWhatToBringListController.php"
    - "/app/Http/Controllers/ManageSubscriptionsController.php"
    - "/app/Http/Controllers/MessageController"
    - "/app/Http/Controllers/SearchController"