coverage:
  precision: 2
  round: nearest
  range: "40...100"
  status:
    project:
      default:
        threshold: 3
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
